import React from 'react';

const MarksDashboard = ({ student }) => {
  // Debugging: Log the student object to ensure it has the correct structure
  console.log('Student Object:', student);

  // Destructure marks object from student
  const { branch, semester, subject, marks } = student;

  return (
    <div className="max-w-4xl mx-auto bg-white shadow-lg rounded-lg p-8 mt-8">
      <div className="text-center">
        <h2 className="text-2xl font-semibold text-gray-900 font-dosis">Mid Semester Marks Statement</h2>
        <p className="text-gray-800 font-dosis">Date : {new Date().toLocaleDateString()} , Time : {new Date().toLocaleTimeString()}</p>
      </div>
      <div className="mt-8">
        <p className="text-gray-900 font-dosis"><strong>Student Name:</strong> {marks?.name || 'N/A'}</p>
        <p className="text-gray-900 font-dosis"><strong>Enrollment Number:</strong> {marks?.enrolment || 'N/A'}</p>
        <p className="text-gray-900 font-dosis"><strong>Semester:</strong> {semester || 'N/A'}</p>
        <p className="text-gray-900 font-dosis"><strong>Branch:</strong> {branch || 'N/A'}</p>
      </div>
      <div className="mt-6">
        <h3 className="text-lg font-medium mb-4 text-gray-900 text-center font-dosis">Marks Statement</h3>
        <table className="min-w-full bg-white border border-gray-300">
          <thead>
            <tr>
              <th className="py-2 px-4 bg-gray-200 border-b border-gray-300 text-gray-900 text-left font-dosis">Subject Name</th>
              <th className="py-2 px-4 bg-gray-200 border-b border-gray-300 text-gray-900 text-left font-dosis">Marks Obtained</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="py-2 px-4 text-gray-800 font-dosis">{subject || 'N/A'}</td>
              <td className="py-2 px-4 text-gray-800 font-dosis">{marks?.marks || 'N/A'}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div className="mt-4 bg-blue-100 text-center text-blue-800 py-2 rounded-lg font-dosis">
        You have passed the midsem examination ✨
      </div>
      <div className="mt-8 text-center text-sm text-gray-600 font-dosis">
        Marksheet report is generated by {marks?.name || 'N/A'}.
      </div>
    </div>
  );
};

export default MarksDashboard;
